### ISSUE TITLE
Repo Organization

### ISSUE THREAD

**Issue by bemcdonnell** [dickinsonre/SWMM123456#1]
@dickinsonre, I'm not sure if you're considering contributing code in down the road to a common repository. If so, instead of initializing your own repo, it is better to "Fork" a repo.  That way if you submit a pull request, it will come through only as the small changes to files as opposed to adding files. 

If you already knew this, sorry for making noise :)

**Comment by dickinsonre** [comment]
To be honest this is an experimental GitHub to help me organize my various versions of code.  Git has nice features for comparing code so I thought I would try it out again.  The desktop Git did not seem to work for me.
